DIR_LAB               = lab
NAME                  = spring-engineering-guides
IMAGE_SOURCE          = https://github.com/spring-academy/spring-engineering-guides
CONTAINER_REGISTRY    = 
CONTAINER_REPOSITORY  = spring-engineering-guides
version               = latest

env                   = local