apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: spr-eng-guides-restclient-httpinterfaces
spec:
  title: HTTP Interfaces in Spring Boot
  description: "This lab will demonstrate HTTP Interfaces using Spring MVC"
  workshop:
    image: jdk17-environment:*
    files:
      - image: # Note: format is {repository-name}-files
          url: $(image_repository)/spring-engineering-guides-files:$(workshop_version)
        includePaths:
          - /workshops/10-restclient-httpinterfaces/workshop/**
        newRootPath: workshops/10-restclient-httpinterfaces
      - path: .local/share/code-server
        image:
          url: ghcr.io/spring-academy/vscode-java-tools-$(platform_arch)-files:0.25.14
      - path: exercises
        git:
          url: https://github.com/robertmcnees/spring-academy-restclient-httpinterfaces
          ref: main
        newRootPath: .
  request:
    parameters:
    - name: USER_DOMAIN
      value: "unknown.domain"
    - name: USER_EMAIL
      value: "somebody@unknown.domain"
  session:
    namespaces:
      budget: medium
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
      editor:
        enabled: true
    dashboards:
      - name: Editor
      - name: Terminal
