apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: spr-eng-guides-what-is-new-spring-boot-3-2
spec:
  title: What Is New in Spring Boot 3.2
  description: "This lab will demonstrate what is new in Spring Boot 3.2"
  workshop:
    image: jdk17-environment:*
    files:
      - image: # Note: format is {repository-name}-files
          url: $(image_repository)/spring-engineering-guides-files:$(workshop_version)
        includePaths:
          - /workshops/07-what-is-new-spring-boot-3-2/workshop/**
        newRootPath: workshops/07-what-is-new-spring-boot-3-2
      - path: .local/share/code-server
        image:
          url: ghcr.io/spring-academy/vscode-java-tools-$(platform_arch)-files:0.25.14
      - path: exercises
        git:
          url: https://github.com/robertmcnees/spring-academy-boot-3-2
          ref: main
        newRootPath: .
  request:
    parameters:
    - name: USER_DOMAIN
      value: "unknown.domain"
    - name: USER_EMAIL
      value: "somebody@unknown.domain"
  session:
    namespaces:
      budget: medium
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
    dashboards:
      - name: Editor
      - name: Terminal
